name: CI
on:
  push:
    branches: [main]
env:
  BRANCH: ${GITHUB_REF#refs/heads/}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref
      - name: Run exclude
        run: echo ${{ steps.myref.outputs.branch }} ${{ env.BRANCH }} 