name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Prints basic head
        shell: bash
        run: echo "${{ GITHUB_REF#refs/heads/ }}"

