name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Prints the current branch name
        run: echo "$GITHUB_BRANCH"
        env:
          GITHUB_BRANCH: ${{ github.ref }}

