name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch ${{ env.GITHUB_HEAD_REF }}

      - name: Branch1 name
        run: echo running on branch ${{ github.head_ref }}
      - name: Branch2 name
        run: echo running on branch ${{ github.ref }}
      - name: Branch3 name
        run: echo running on branch ${{ GITHUB_REF##*/ }}
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
